url: http://www.tingweili.com

# Site settings
title: Tingwei Li
email: annecylee@gmail.com
description: "Tingwei Li's portfolio"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: www.linkedin.com/in/tingweli

# build settings
markdown: kramdown
permalink: pretty
